#!/usr/bin/env python

import sys
import time
import serial


input = open(sys.argv[1], 'rb')
port = serial.Serial('COM4', 115200, timeout=0)

port.write('a:recvbin ')
port.write(sys.argv[2])
port.write(chr(13))
time.sleep(1);
sent = 0
while True:
    data = input.read(128)
    if data == '':
        break
    #tx = ''.join('%02X' % ord(char) for char in data)
    tx=data
    if len(tx) < 128: # pad to 128 bytes
        tx = tx + (chr(0) * (128 - len(tx)))
    port.write('@') # framing byte
    port.write(tx)
    port.flush()
    time.sleep(float(len(tx)+10) / 11000.)
    sent += len(data)
    if sent % 16384 == 0:
        # a little extra sleep every 16KB
        time.sleep(0.05)

time.sleep(0.05)
port.write('!')
